# -*- coding: utf-8 -*-
import pathlib
path = pathlib.Path('frontend/src/pages/DocumentManagerPage.tsx')
txt = path.read_text(encoding='utf-8')
old = """  const wrapperClassName = standaloneView ? \"mx-auto flex max-w-6xl flex-col gap-6\" : \"space-y-6\";\n  const headerContent = standaloneView ? (\n    <div className=\"rounded-2xl border border-slate-200 bg-white p-6 shadow-sm\">\n      <div className=\"flex flex-col gap-4 md:flex-row md:items-start md:justify-between\">\n        <div className=\"space-y-2\">\n          <p className=\"text-xs font-semibold uppercase tracking-wide text-indigo-500\">Fluxo do documento</p>\n          <h1 className=\"text-2xl font-semibold text-slate-900\">\n            {selectedDocument?.name ?? \"Carregando documento...\"}\n          </h1>\n          <p className=\"text-sm text-slate-500\">\n            {selectedDocument\n              ? `ltima atualizao ${formatDateTime(selectedDocument.updated_at ?? selectedDocument.created_at)}`\n              : \"Buscando informaes do documento selecionado.\"}\n          </p>\n        </div>\n        <div className=\"flex flex-wrap items-center gap-2\">\n          {selectedDocument && (\n            <span className=\"inline-flex items-center rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-semibold text-slate-600\">\n              Status: {formatStatusLabel(selectedDocument.status)}\n            </span>\n          )}\n          {icpStatus && (\n            <span className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold ${icpStatus.tone}`}>\n              {icpStatus.label}\n            </span>\n          )}\n        </div>\n      </div>\n      {standaloneError && (\n        <div className=\"mt-4 rounded-md border border-rose-200 bg-rose-50 px-4 py-2 text-sm text-rose-700\">\n          {standaloneError}\n        </div>\n      )}\n    </div>\n  ) : (\n    <div className=\"flex flex-col gap-2\">\n      <div className=\"flex items-center justify-between\">\n        <h1 className=\"text-2xl font-semibold\">Documentos</h1>\n        {icpStatus && (\n          <span className={`text-sm font-medium ${icpStatus.tone}`}>\n            {icpStatus.label}\n          </span>\n        )}\n      </div>\n    </div>\n  );\n"""
new = """  const wrapperClassName = standaloneView ? \"mx-auto flex max-w-6xl flex-col gap-6\" : \"space-y-6\";\n  const headerContent = standaloneView || focusMode ? (\n    <div className=\"rounded-2xl border border-slate-200 bg-white p-6 shadow-sm\">\n      <div className=\"flex flex-col gap-4 md:flex-row md:items-start md:justify-between\">\n        <div className=\"space-y-2\">\n          <p className=\"text-xs font-semibold uppercase tracking-wide text-indigo-500\">Fluxo do documento</p>\n          <h1 className=\"text-2xl font-semibold text-slate-900\">\n            {selectedDocument?.name ?? \"Carregando documento...\"}\n          </h1>\n          <p className=\"text-sm text-slate-500\">\n            {selectedDocument\n              ? `Última atualização ${formatDateTime(selectedDocument.updated_at ?? selectedDocument.created_at)}`\n              : \"Buscando informações do documento selecionado.\"}\n          </p>\n        </div>\n        <div className=\"flex flex-wrap items-center gap-2\">\n          {selectedDocument && (\n            <span className=\"inline-flex items-center rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-semibold text-slate-600\">\n              Status: {formatStatusLabel(selectedDocument.status)}\n            </span>\n          )}\n          {icpStatus && (\n            <span className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold ${icpStatus.tone}`}>\n              {icpStatus.label}\n            </span>\n          )}\n        </div>\n      </div>\n      {standaloneError && standaloneView && (\n        <div className=\"mt-4 rounded-md border border-rose-200 bg-rose-50 px-4 py-2 text-sm text-rose-700\">\n          {standaloneError}\n        </div>\n      )}\n    </div>\n  ) : (\n    <div className=\"flex flex-col gap-2\">\n      <div className=\"flex items-center justify-between\">\n        <h1 className=\"text-2xl font-semibold\">Documentos</h1>\n        {icpStatus && (\n          <span className={`text-sm font-medium ${icpStatus.tone}`}>\n            {icpStatus.label}\n          </span>\n        )}\n      </div>\n    </div>\n  );\n"""
if old not in txt:
    raise SystemExit('pattern not found')
txt = txt.replace(old, new, 1)
path.write_text(txt, encoding='utf-8')
