"""
Revision ID: c5a62b19a879
Revises: 0001_initial
Create Date: 2025-10-08 02:13:17.721006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision = 'c5a62b19a879'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic (made idempotent) ###
    bind = op.get_bind()
    insp = inspect(bind)
    cols = {c['name'] for c in insp.get_columns('tenants')} if insp.has_table('tenants') else set()
    if 'balance_cents' not in cols:
        op.add_column('tenants', sa.Column('balance_cents', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic (made idempotent) ###
    bind = op.get_bind()
    insp = inspect(bind)
    if insp.has_table('tenants'):
        cols = {c['name'] for c in insp.get_columns('tenants')}
        if 'balance_cents' in cols:
            op.drop_column('tenants', 'balance_cents')
    # ### end Alembic commands ###
